import { createTheme, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import "@mantine/core/styles.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";

import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "atomicmvp.com",
  description: "Generated by maxheredia95@gmail.com",
};
const theme = createTheme({
  /** Put your mantine theme override here */
});

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = (await import(`../../../messages/${locale}.json`)).default;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <MantineProvider theme={theme}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
